# This is a basic workflow to help you get started with Actions

name: Basic CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_js:
    name: Testing Environments
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      # Runs a single command using the runners shell
      - name: Install Dependencies
        run: echo "Installing"
      - name: Run Tests
        run: echo "Testing"
      - name: Run Validation
        run: echo "Validate"
      - name: Run Build
        run: echo "Build"
  deploy_to_int:
    name: Deploy to Int
    needs: build_js
    concurrency:
      group: ${{ github.ref }}-int
      cancel-in-progress: false
    runs-on: ubuntu-latest
    environment: int
    steps:
      - name: deploy
        run: echo "We are deploying to int"
  deploy_to_qa:
    name: Deploy to QA
    needs: deploy_to_int
    concurrency:
      group: ${{ github.ref }}-qa
      cancel-in-progress: false
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: deploy
        run: echo "We are deploying to qa"
  lock_for_prod:
    name: Lock For Prod
    needs: deploy_to_qa
    concurrency:
      group: ${{ github.ref }}-lock
      cancel-in-progress: true
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: lock
        run: echo "Ok, this shit is locked"
  deploy_to_prod:
    name: Deploy to Prod
    needs: lock_for_prod
    concurrency:
      group: ${{ github.ref }}-prod
      cancel-in-progress: false
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy
        run: echo "We are deploying to prod"
